DROP PROCEDURE NO_PARAM;
DROP PROCEDURE SIMPLETYPE_PARAM;
DROP PROCEDURE DTO_PARAM;
DROP PROCEDURE ONE_RESULT;
DROP PROCEDURE TWO_RESULTS;

DROP TABLE ADDRESS;
DROP TABLE DEPARTMENT;
DROP TABLE EMPLOYEE;