DROP PROCEDURE NO_PARAM;
DROP PROCEDURE SIMPLETYPE_PARAM;
DROP PROCEDURE DTO_PARAM;
DROP PROCEDURE ONE_RESULT;
DROP PROCEDURE TWO_RESULTS;

DROP TABLE EMPLOYEE;
DROP TABLE ADDRESS;
DROP TABLE DEPARTMENT;

DROP TABLE COMP_KEY_EMPLOYEE;
DROP TABLE COMP_KEY_ADDRESS;
DROP TABLE COMP_KEY_DEPARTMENT;

DROP TABLE LARGE_OBJECT;

DROP TABLE ID_GENERATOR;
DROP TABLE MY_ID_GENERATOR;
DROP TABLE AUTO_STRATEGY;
DROP TABLE IDENTITY_STRATEGY;
DROP TABLE SEQUENCE_STRATEGY;
DROP TABLE SEQUENCE_STRATEGY2;
DROP TABLE TABLE_STRATEGY;
DROP TABLE TABLE_STRATEGY2;