DROP PROCEDURE PROC_NONE_PARAM;
DROP PROCEDURE PROC_SIMPLETYPE_PARAM;
DROP PROCEDURE PROC_DTO_PARAM;
DROP PROCEDURE PROC_RESULTSET;
DROP PROCEDURE PROC_RESULTSET_OUT;
DROP PROCEDURE PROC_RESULTSET_UPDATE;
DROP PROCEDURE PROC_RESULTSETS;
DROP PROCEDURE PROC_RESULTSETS_UPDATES_OUT;

DROP TABLE EMPLOYEE;
DROP TABLE ADDRESS;
DROP TABLE DEPARTMENT;

DROP TABLE COMP_KEY_EMPLOYEE;
DROP TABLE COMP_KEY_ADDRESS;
DROP TABLE COMP_KEY_DEPARTMENT;

DROP TABLE LARGE_OBJECT;

DROP TABLE ID_GENERATOR;
DROP TABLE MY_ID_GENERATOR;
DROP TABLE AUTO_STRATEGY;
DROP TABLE IDENTITY_STRATEGY;
DROP TABLE SEQUENCE_STRATEGY;
DROP TABLE SEQUENCE_STRATEGY2;
DROP TABLE TABLE_STRATEGY;
DROP TABLE TABLE_STRATEGY2;