DROP PROCEDURE NO_PARAM;
DROP PROCEDURE SIMPLETYPE_PARAM;
DROP PROCEDURE DTO_PARAM;
DROP PROCEDURE ONE_RESULT;
DROP PROCEDURE TWO_RESULTS;

DROP TABLE EMPLOYEE;
DROP TABLE ADDRESS;
DROP TABLE DEPARTMENT;

DROP TABLE COMP_KEY_EMPLOYEE;
DROP TABLE COMP_KEY_ADDRESS;
DROP TABLE COMP_KEY_DEPARTMENT;
