DROP TABLE EMPLOYEE;
DROP TABLE ADDRESS;
DROP TABLE DEPARTMENT;

DROP TABLE COMP_KEY_EMPLOYEE;
DROP TABLE COMP_KEY_ADDRESS;
DROP TABLE COMP_KEY_DEPARTMENT;

DROP TABLE LARGE_OBJECT;
DROP TABLE TENSE;
DROP TABLE JOB;
DROP TABLE AUTHORITY;

DROP TABLE ID_GENERATOR;
DROP TABLE MY_ID_GENERATOR;
DROP TABLE AUTO_STRATEGY;
DROP TABLE TABLE_STRATEGY;
DROP TABLE TABLE_STRATEGY2;
