CREATE TABLE BINARY_DOUBLE_TYPE (BINARY_DOUBLE_COL BINARY_DOUBLE);
CREATE TABLE BINARY_FLOAT_TYPE (BINARY_FLOAT_COL BINARY_FLOAT);
CREATE TABLE BLOB_TYPE (BLOB_COL BLOB);
CREATE TABLE CHAR_TYPE (CHAR_COL CHAR(1));
CREATE TABLE CLOB_TYPE (CLOB_COL CLOB);
CREATE TABLE DATE_TYPE (DATE_COL DATE);
CREATE TABLE FLOAT_TYPE (FLOAT_COL FLOAT);
CREATE TABLE LONG_TYPE (LONG_COL LONG);
CREATE TABLE LONG_RAW_TYPE (LONG_RAW_COL LONG RAW);
CREATE TABLE NCHAR_TYPE (NCHAR_COL NCHAR(1));
CREATE TABLE NUMBER_TYPE (NUMBER_COL NUMBER(10,5));
CREATE TABLE NVARCHAR2_TYPE (NVARCHAR2_COL NVARCHAR2(2000));
CREATE TABLE RAW_TYPE (RAW_COL RAW(2000));
CREATE TABLE TIMESTAMP_TYPE (TIMESTAMP_COL TIMESTAMP);
CREATE TABLE UROWID_TYPE (UROWID_COL UROWID (4000));
CREATE TABLE VARCHAR2_TYPE (VARCHAR2_COL VARCHAR2(4000));

CREATE TABLE SCHEMA_INFO (VERSION NUMBER(8));
INSERT INTO SCHEMA_INFO VALUES(0);