create table binary_double_table (binary_double_column binary_double);
create table binary_float_table (binary_float_column binary_float);
create table blob_table (blob_column blob);
create table char_table (char_column char(1));
create table clob_table (clob_column clob);
create table date_table (date_column date);
create table float_table (float_column float);
create table long_table (long_column long);
create table long_raw_table (long_raw_column long raw);
create table nchar_table (nchar_column nchar(1));
create table number_table (number_column number(10,5));
create table nvarchar2_table (nvarchar2_column nvarchar2(2000));
create table raw_table (raw_column raw(2000));
create table timestamp_table (timestamp_column timestamp);
create table urowid_table (urowid_column urowid (4000));
create table varchar2_table (varchar2_column varchar2(4000));