DROP TABLE BINARY_DOUBLE_TYPE;
DROP TABLE BINARY_FLOAT_TYPE;
DROP TABLE BLOB_TYPE;
DROP TABLE CHAR_TYPE;
DROP TABLE CLOB_TYPE;
DROP TABLE DATE_TYPE;
DROP TABLE FLOAT_TYPE;
DROP TABLE LONG_TYPE;
DROP TABLE LONG_RAW_TYPE;
DROP TABLE NCHAR_TYPE;
DROP TABLE NUMBER_TYPE;
DROP TABLE NVARCHAR2_TYPE;
DROP TABLE RAW_TYPE;
DROP TABLE TIMESTAMP_TYPE;
DROP TABLE UROWID_TYPE;
DROP TABLE VARCHAR2_TYPE;

DROP TABLE SCHEMA_INFO;